//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Resource.rc で使用
//
#define IDB_BLACK_PUYOPUYO_NORMAL								101
#define IDB_BULE_PUYOPUYO_CONNECT_BOTTOM						102
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT							103
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT_BOTTOM					104
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT_RIGHT					105
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT_RIGHT_BOTTOM				106
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT_TOP						107
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT_TOP_BOTTOM				108
#define IDB_BULE_PUYOPUYO_CONNECT_LEFT_TOP_RIGTH				109
#define IDB_BULE_PUYOPUYO_CONNECT_ALL							110
#define IDB_BULE_PUYOPUYO_NORMAL								111
#define IDB_BULE_PUYOPUYO_CONNECT_RIGHT							112
#define IDB_BULE_PUYOPUYO_CONNECT_RIGHT_BOTTOM					113
#define IDB_BULE_PUYOPUYO_CONNECT_TOP							114
#define IDB_BULE_PUYOPUYO_CONNECT_TOP_BOTTOM					115
#define IDB_BULE_PUYOPUYO_CONNECT_TOP_RIGHT						116
#define IDB_BULE_PUYOPUYO_CONNECT_TOP_RIGHT_BOTTOM				117
#define IDB_GREEN_PUYOPUYO_CONNECT_BOTTOM						118
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT							119
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT_BOTTOM					120
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT_RIGHT					121
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT_RIGHT_BOTTOM			122
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT_TOP						123
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT_TOP_BOTTOM				124
#define IDB_GREEN_PUYOPUYO_CONNECT_LEFT_TOP_RIGTH				125
#define IDB_GREEN_PUYOPUYO_CONNECT_ALL							126
#define IDB_GREEN_PUYOPUYO_NORMAL								127
#define IDB_GREEN_PUYOPUYO_CONNECT_RIGHT						128
#define IDB_GREEN_PUYOPUYO_CONNECT_RIGHT_BOTTOM					129
#define IDB_GREEN_PUYOPUYO_CONNECT_TOP							130
#define IDB_GREEN_PUYOPUYO_CONNECT_TOP_BOTTOM					131
#define IDB_GREEN_PUYOPUYO_CONNECT_TOP_RIGHT					132
#define IDB_GREEN_PUYOPUYO_CONNECT_TOP_RIGHT_BOTTOM				133
#define IDB_PURPLE_PUYOPUYO_CONNECT_BOTTOM						134
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT						135
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT_BOTTOM					136
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT_RIGHT					137
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT_RIGHT_BOTTOM			138
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT_TOP					139
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT_TOP_BOTTOM				140
#define IDB_PURPLE_PUYOPUYO_CONNECT_LEFT_TOP_RIGTH				141
#define IDB_PURPLE_PUYOPUYO_CONNECT_ALL							142
#define IDB_PURPLE_PUYOPUYO_NORMAL								143
#define IDB_PURPLE_PUYOPUYO_CONNECT_RIGHT						144
#define IDB_PURPLE_PUYOPUYO_CONNECT_RIGHT_BOTTOM				145
#define IDB_PURPLE_PUYOPUYO_CONNECT_TOP							146
#define IDB_PURPLE_PUYOPUYO_CONNECT_TOP_BOTTOM					147
#define IDB_PURPLE_PUYOPUYO_CONNECT_TOP_RIGHT					148
#define IDB_PURPLE_PUYOPUYO_CONNECT_TOP_RIGHT_BOTTOM			149
#define IDB_RED_PUYOPUYO_CONNECT_BOTTOM							150
#define IDB_RED_PUYOPUYO_CONNECT_LEFT							151
#define IDB_RED_PUYOPUYO_CONNECT_LEFT_BOTTOM					152
#define IDB_RED_PUYOPUYO_CONNECT_LEFT_RIGHT						153
#define IDB_RED_PUYOPUYO_CONNECT_LEFT_RIGHT_BOTTOM				154
#define IDB_RED_PUYOPUYO_CONNECT_LEFT_TOP_BOTTOM				155
#define IDB_RED_PUYOPUYO_CONNECT_LEFT_TOP_RIGTH					156
#define IDB_RED_PUYOPUYO_CONNECT_ALL							157
#define IDB_RED_PUYOPUYO_NORMAL									158
#define IDB_RED_PUYOPUYO_CONNECT_RIGHT							159
#define IDB_RED_PUYOPUYO_CONNECT_RIGHT_BOTTOM					160
#define IDB_RED_PUYOPUYO_CONNECT_LEFT_TOP						161
#define IDB_RED_PUYOPUYO_CONNECT_TOP							162
#define IDB_RED_PUYOPUYO_CONNECT_TOP_BOTTOM						163
#define IDB_RED_PUYOPUYO_CONNECT_TOP_RIGHT						164
#define IDB_RED_PUYOPUYO_CONNECT_TOP_RIGHT_BOTTOM				165
#define IDB_YELLOW_PUYOPUYO_CONNECT_BOTTOM						166
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT						167
#define IDB_BITMAP68											168
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT_BOTTOM					168
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT_RIGHT					169
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT_RIGHT_BOTTOM			170
#define IDB_YELLOW_PUYOPUYO_CONNECT_ALL							171
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT_TOP					172
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT_TOP_BOTTOM				173
#define IDB_YELLOW_PUYOPUYO_CONNECT_LEFT_TOP_RIGTH				174
#define IDB_YELLOW_PUYOPUYO_NORMAL								175
#define IDB_YELLOW_PUYOPUYO_CONNECT_RIGHT						176
#define IDB_YELLOW_PUYOPUYO_CONNECT_RIGHT_BOTTOM				177
#define IDB_YELLOW_PUYOPUYO_CONNECT_TOP							178
#define IDB_YELLOW_PUYOPUYO_CONNECT_TOP_BOTTOM					179
#define IDB_YELLOW_PUYOPUYO_CONNECT_TOP_RIGHT					180
#define IDB_YELLOW_PUYOPUYO_CONNECT_TOP_RIGHT_BOTTOM			181

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
